cogs:
- any:
  - changed-files:
    - any-glob-to-any-file: 'src/cogs/**'


handler:
- any:
  - changed-files:
    - any-glob-to-any-file: 'src/handler/**'

documentation:
- any:
  - changed-files:
    - any-glob-to-any-file: 'docs/**'
    - any-glob-to-any-file: '**/*.md'

site:
- any:
  - changed-files:
    - any-glob-to-any-file: 'src/web/**'

example:
- any:
  - changed-files:
    - any-glob-to-any-file: 'examples/**'

translation-message:
- any:
  - changed-files:
    - any-glob-to-any-file: 'translation/message/**'

translation-commands:
- any:
  - changed-files:
    - any-glob-to-any-file: 'translation/commands/**'

translation:
- any:
  - changed-files:
    - any-glob-to-any-file: 'translation/**'

python:
- any:
  - changed-files:
    - any-glob-to-any-file: '**/*.py'

javascript:
- any:
  - changed-files:
    - any-glob-to-any-file: '**/*.js'

html:
- any:
  - changed-files:
    - any-glob-to-any-file: '**/*.html'

css:
- any:
  - changed-files:
    - any-glob-to-any-file: '**/*.css'

api:
- any:
  - changed-files:
    - any-glob-to-any-file: '**/api.py'
    - any-glob-to-any-file: '**/api.js'

